// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMf6_XLeDDvZ2wfNhEAJsm3Uj5e3IDmf4',
    appId: '1:340327251512:web:6a00485fc56d453f24f0cd',
    messagingSenderId: '340327251512',
    projectId: 'clients-790b9',
    authDomain: 'clients-790b9.firebaseapp.com',
    storageBucket: 'clients-790b9.appspot.com',
    measurementId: 'G-XFNV5YMXTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpF_KYOA9abQ3lu6-WCbBTDbpTZ7zwJMU',
    appId: '1:340327251512:android:65e36d5cd9188e2224f0cd',
    messagingSenderId: '340327251512',
    projectId: 'clients-790b9',
    storageBucket: 'clients-790b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1uI-_z36TH_pPWrz9HfREwgRvbtBES6Y',
    appId: '1:340327251512:ios:d81198a416ec623c24f0cd',
    messagingSenderId: '340327251512',
    projectId: 'clients-790b9',
    storageBucket: 'clients-790b9.appspot.com',
    iosBundleId: 'com.example.clients',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1uI-_z36TH_pPWrz9HfREwgRvbtBES6Y',
    appId: '1:340327251512:ios:d81198a416ec623c24f0cd',
    messagingSenderId: '340327251512',
    projectId: 'clients-790b9',
    storageBucket: 'clients-790b9.appspot.com',
    iosBundleId: 'com.example.clients',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMf6_XLeDDvZ2wfNhEAJsm3Uj5e3IDmf4',
    appId: '1:340327251512:web:d1004bf2dc6f849424f0cd',
    messagingSenderId: '340327251512',
    projectId: 'clients-790b9',
    authDomain: 'clients-790b9.firebaseapp.com',
    storageBucket: 'clients-790b9.appspot.com',
    measurementId: 'G-X4LJN9R7WP',
  );
}
